import re
new_file=input('input a filename as the new fasta file: ')
if re.search(r'.fa$',new_file):
	file=open('Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa')
	results=open(f'{new_file}','w')
	DNA = file.read()
	DNA = ''.join(DNA.split('\n'))
	DNA = DNA.lstrip('>')
	genes=re.split(r'>',DNA)
	output=''
	for i in range(len(genes)):
		if re.search(r'GAATTC',genes[i]):
			name=str(re.findall(r'gene:(.+?)\s',genes[i]))
			x=str(re.findall(r'](.+)',genes[i]))
			x=x.strip("[']")
			number=b.count('GAATTC')+1
			output=output+'>'+'\n'+'The number of fragments which could be generated by EcoRI is '+str(number)+'\n'+'Sequence:'+x+'\n'
results.write(output)
file.close()
results.close()